services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - HUGGINGFACE_TOKEN=${HUGGINGFACE_TOKEN}
      - MODEL_PATH=${MODEL_PATH:-./models/tinyllama-finetuned}
      - ENVIRONMENT=${ENVIRONMENT:-production}
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3

  bot:
    build: ./bot
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - API_URL=http://api:8000/api/chat
    depends_on:
      api:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./deployment/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./deployment/ssl:/etc/ssl/certs:ro
    depends_on:
      - api
    restart: unless-stopped